# Dockerfile for CI testing environment on GitHub Actions:

version: "3.9"

services:
  db:
    image: postgres:14
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mygreatproject

volumes:
  postgres-data:
    driver: local
